// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: controlplane/v1/configuration.proto

package controlplanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncRequest_Registration
	//	*SyncRequest_Ack
	//	*SyncRequest_Nack
	//	*SyncRequest_Heartbeat
	Payload       isSyncRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetPayload() isSyncRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncRequest) GetRegistration() *Registration {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Registration); ok {
			return x.Registration
		}
	}
	return nil
}

func (x *SyncRequest) GetAck() *Acknowledgement {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *SyncRequest) GetNack() *Rejection {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

func (x *SyncRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*SyncRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isSyncRequest_Payload interface {
	isSyncRequest_Payload()
}

type SyncRequest_Registration struct {
	Registration *Registration `protobuf:"bytes,1,opt,name=registration,proto3,oneof"`
}

type SyncRequest_Ack struct {
	Ack *Acknowledgement `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type SyncRequest_Nack struct {
	Nack *Rejection `protobuf:"bytes,3,opt,name=nack,proto3,oneof"`
}

type SyncRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*SyncRequest_Registration) isSyncRequest_Payload() {}

func (*SyncRequest_Ack) isSyncRequest_Payload() {}

func (*SyncRequest_Nack) isSyncRequest_Payload() {}

func (*SyncRequest_Heartbeat) isSyncRequest_Payload() {}

type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncResponse_Snapshot
	//	*SyncResponse_Heartbeat
	Payload       isSyncResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetPayload() isSyncResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncResponse) GetSnapshot() *ConfigurationSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *SyncResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*SyncResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isSyncResponse_Payload interface {
	isSyncResponse_Payload()
}

type SyncResponse_Snapshot struct {
	Snapshot *ConfigurationSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type SyncResponse_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

func (*SyncResponse_Snapshot) isSyncResponse_Payload() {}

func (*SyncResponse_Heartbeat) isSyncResponse_Payload() {}

type Registration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstanceId      string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ProtocolVersion uint32                 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AppliedRevision string                 `protobuf:"bytes,3,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Registration) Reset() {
	*x = Registration{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registration) ProtoMessage() {}

func (x *Registration) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registration.ProtoReflect.Descriptor instead.
func (*Registration) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *Registration) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Registration) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Registration) GetAppliedRevision() string {
	if x != nil {
		return x.AppliedRevision
	}
	return ""
}

type Acknowledgement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{3}
}

func (x *Acknowledgement) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Acknowledgement) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

type Rejection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rejection) Reset() {
	*x = Rejection{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rejection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rejection) ProtoMessage() {}

func (x *Rejection) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rejection.ProtoReflect.Descriptor instead.
func (*Rejection) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{4}
}

func (x *Rejection) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Rejection) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *Rejection) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *Rejection) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{5}
}

type ConfigurationSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Configuration *DynamicConfiguration  `protobuf:"bytes,4,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationSnapshot) Reset() {
	*x = ConfigurationSnapshot{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSnapshot) ProtoMessage() {}

func (x *ConfigurationSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigurationSnapshot) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigurationSnapshot) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ConfigurationSnapshot) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ConfigurationSnapshot) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ConfigurationSnapshot) GetConfiguration() *DynamicConfiguration {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type DynamicConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiClients    []*ApiClient           `protobuf:"bytes,1,rep,name=api_clients,json=apiClients,proto3" json:"api_clients,omitempty"`
	Routes        []*Route               `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicConfiguration) Reset() {
	*x = DynamicConfiguration{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicConfiguration) ProtoMessage() {}

func (x *DynamicConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicConfiguration.ProtoReflect.Descriptor instead.
func (*DynamicConfiguration) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{7}
}

func (x *DynamicConfiguration) GetApiClients() []*ApiClient {
	if x != nil {
		return x.ApiClients
	}
	return nil
}

func (x *DynamicConfiguration) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type ApiClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiClient) Reset() {
	*x = ApiClient{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiClient) ProtoMessage() {}

func (x *ApiClient) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiClient.ProtoReflect.Descriptor instead.
func (*ApiClient) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{8}
}

func (x *ApiClient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApiClient) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ApiClient) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PathPrefix    string                 `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Upstream      string                 `protobuf:"bytes,3,opt,name=upstream,proto3" json:"upstream,omitempty"`
	TimeoutNanos  int64                  `protobuf:"varint,4,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	Auth          *AuthenticationPolicy  `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	RateLimit     *RateLimitPolicy       `protobuf:"bytes,6,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Waf           *WafPolicy             `protobuf:"bytes,7,opt,name=waf,proto3" json:"waf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{9}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Route) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *Route) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

func (x *Route) GetAuth() *AuthenticationPolicy {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Route) GetRateLimit() *RateLimitPolicy {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *Route) GetWaf() *WafPolicy {
	if x != nil {
		return x.Waf
	}
	return nil
}

type AuthenticationPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	RequiredScopes []string               `protobuf:"bytes,2,rep,name=required_scopes,json=requiredScopes,proto3" json:"required_scopes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthenticationPolicy) Reset() {
	*x = AuthenticationPolicy{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationPolicy) ProtoMessage() {}

func (x *AuthenticationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationPolicy.ProtoReflect.Descriptor instead.
func (*AuthenticationPolicy) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{10}
}

func (x *AuthenticationPolicy) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *AuthenticationPolicy) GetRequiredScopes() []string {
	if x != nil {
		return x.RequiredScopes
	}
	return nil
}

type RateLimitPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Capacity        int64                  `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	RefillPerSecond float64                `protobuf:"fixed64,2,opt,name=refill_per_second,json=refillPerSecond,proto3" json:"refill_per_second,omitempty"`
	OnRedisError    string                 `protobuf:"bytes,3,opt,name=on_redis_error,json=onRedisError,proto3" json:"on_redis_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RateLimitPolicy) Reset() {
	*x = RateLimitPolicy{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitPolicy) ProtoMessage() {}

func (x *RateLimitPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitPolicy.ProtoReflect.Descriptor instead.
func (*RateLimitPolicy) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{11}
}

func (x *RateLimitPolicy) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *RateLimitPolicy) GetRefillPerSecond() float64 {
	if x != nil {
		return x.RefillPerSecond
	}
	return 0
}

func (x *RateLimitPolicy) GetOnRedisError() string {
	if x != nil {
		return x.OnRedisError
	}
	return ""
}

type WafPolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mode             string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	RuleSet          string                 `protobuf:"bytes,2,opt,name=rule_set,json=ruleSet,proto3" json:"rule_set,omitempty"`
	AnomalyThreshold int32                  `protobuf:"varint,3,opt,name=anomaly_threshold,json=anomalyThreshold,proto3" json:"anomaly_threshold,omitempty"`
	Inspection       *InspectionPolicy      `protobuf:"bytes,4,opt,name=inspection,proto3" json:"inspection,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WafPolicy) Reset() {
	*x = WafPolicy{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WafPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WafPolicy) ProtoMessage() {}

func (x *WafPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WafPolicy.ProtoReflect.Descriptor instead.
func (*WafPolicy) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{12}
}

func (x *WafPolicy) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *WafPolicy) GetRuleSet() string {
	if x != nil {
		return x.RuleSet
	}
	return ""
}

func (x *WafPolicy) GetAnomalyThreshold() int32 {
	if x != nil {
		return x.AnomalyThreshold
	}
	return 0
}

func (x *WafPolicy) GetInspection() *InspectionPolicy {
	if x != nil {
		return x.Inspection
	}
	return nil
}

type InspectionPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           bool                   `protobuf:"varint,1,opt,name=query,proto3" json:"query,omitempty"`
	Headers         bool                   `protobuf:"varint,2,opt,name=headers,proto3" json:"headers,omitempty"`
	Body            bool                   `protobuf:"varint,3,opt,name=body,proto3" json:"body,omitempty"`
	MaxQueryBytes   int32                  `protobuf:"varint,4,opt,name=max_query_bytes,json=maxQueryBytes,proto3" json:"max_query_bytes,omitempty"`
	MaxHeaderBytes  int32                  `protobuf:"varint,5,opt,name=max_header_bytes,json=maxHeaderBytes,proto3" json:"max_header_bytes,omitempty"`
	MaxBodyBytes    int32                  `protobuf:"varint,6,opt,name=max_body_bytes,json=maxBodyBytes,proto3" json:"max_body_bytes,omitempty"`
	MaxJsonDepth    int32                  `protobuf:"varint,7,opt,name=max_json_depth,json=maxJsonDepth,proto3" json:"max_json_depth,omitempty"`
	MaxJsonElements int32                  `protobuf:"varint,8,opt,name=max_json_elements,json=maxJsonElements,proto3" json:"max_json_elements,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InspectionPolicy) Reset() {
	*x = InspectionPolicy{}
	mi := &file_controlplane_v1_configuration_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectionPolicy) ProtoMessage() {}

func (x *InspectionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_configuration_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectionPolicy.ProtoReflect.Descriptor instead.
func (*InspectionPolicy) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_configuration_proto_rawDescGZIP(), []int{13}
}

func (x *InspectionPolicy) GetQuery() bool {
	if x != nil {
		return x.Query
	}
	return false
}

func (x *InspectionPolicy) GetHeaders() bool {
	if x != nil {
		return x.Headers
	}
	return false
}

func (x *InspectionPolicy) GetBody() bool {
	if x != nil {
		return x.Body
	}
	return false
}

func (x *InspectionPolicy) GetMaxQueryBytes() int32 {
	if x != nil {
		return x.MaxQueryBytes
	}
	return 0
}

func (x *InspectionPolicy) GetMaxHeaderBytes() int32 {
	if x != nil {
		return x.MaxHeaderBytes
	}
	return 0
}

func (x *InspectionPolicy) GetMaxBodyBytes() int32 {
	if x != nil {
		return x.MaxBodyBytes
	}
	return 0
}

func (x *InspectionPolicy) GetMaxJsonDepth() int32 {
	if x != nil {
		return x.MaxJsonDepth
	}
	return 0
}

func (x *InspectionPolicy) GetMaxJsonElements() int32 {
	if x != nil {
		return x.MaxJsonElements
	}
	return 0
}

var File_controlplane_v1_configuration_proto protoreflect.FileDescriptor

const file_controlplane_v1_configuration_proto_rawDesc = "" +
	"\n" +
	"#controlplane/v1/configuration.proto\x12\x0fcontrolplane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x02\n" +
	"\vSyncRequest\x12C\n" +
	"\fregistration\x18\x01 \x01(\v2\x1d.controlplane.v1.RegistrationH\x00R\fregistration\x124\n" +
	"\x03ack\x18\x02 \x01(\v2 .controlplane.v1.AcknowledgementH\x00R\x03ack\x120\n" +
	"\x04nack\x18\x03 \x01(\v2\x1a.controlplane.v1.RejectionH\x00R\x04nack\x12:\n" +
	"\theartbeat\x18\x04 \x01(\v2\x1a.controlplane.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x9b\x01\n" +
	"\fSyncResponse\x12D\n" +
	"\bsnapshot\x18\x01 \x01(\v2&.controlplane.v1.ConfigurationSnapshotH\x00R\bsnapshot\x12:\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1a.controlplane.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x85\x01\n" +
	"\fRegistration\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12)\n" +
	"\x10applied_revision\x18\x03 \x01(\tR\x0fappliedRevision\"I\n" +
	"\x0fAcknowledgement\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\"~\n" +
	"\tRejection\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x1f\n" +
	"\vreason_code\x18\x03 \x01(\tR\n" +
	"reasonCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\v\n" +
	"\tHeartbeat\"\xdb\x01\n" +
	"\x15ConfigurationSnapshot\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12K\n" +
	"\rconfiguration\x18\x04 \x01(\v2%.controlplane.v1.DynamicConfigurationR\rconfiguration\"\x83\x01\n" +
	"\x14DynamicConfiguration\x12;\n" +
	"\vapi_clients\x18\x01 \x03(\v2\x1a.controlplane.v1.ApiClientR\n" +
	"apiClients\x12.\n" +
	"\x06routes\x18\x02 \x03(\v2\x16.controlplane.v1.RouteR\x06routes\"K\n" +
	"\tApiClient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"\xa3\x02\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12\x1a\n" +
	"\bupstream\x18\x03 \x01(\tR\bupstream\x12#\n" +
	"\rtimeout_nanos\x18\x04 \x01(\x03R\ftimeoutNanos\x129\n" +
	"\x04auth\x18\x05 \x01(\v2%.controlplane.v1.AuthenticationPolicyR\x04auth\x12?\n" +
	"\n" +
	"rate_limit\x18\x06 \x01(\v2 .controlplane.v1.RateLimitPolicyR\trateLimit\x12,\n" +
	"\x03waf\x18\a \x01(\v2\x1a.controlplane.v1.WafPolicyR\x03waf\"S\n" +
	"\x14AuthenticationPolicy\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12'\n" +
	"\x0frequired_scopes\x18\x02 \x03(\tR\x0erequiredScopes\"\x7f\n" +
	"\x0fRateLimitPolicy\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x03R\bcapacity\x12*\n" +
	"\x11refill_per_second\x18\x02 \x01(\x01R\x0frefillPerSecond\x12$\n" +
	"\x0eon_redis_error\x18\x03 \x01(\tR\fonRedisError\"\xaa\x01\n" +
	"\tWafPolicy\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x19\n" +
	"\brule_set\x18\x02 \x01(\tR\aruleSet\x12+\n" +
	"\x11anomaly_threshold\x18\x03 \x01(\x05R\x10anomalyThreshold\x12A\n" +
	"\n" +
	"inspection\x18\x04 \x01(\v2!.controlplane.v1.InspectionPolicyR\n" +
	"inspection\"\xa0\x02\n" +
	"\x10InspectionPolicy\x12\x14\n" +
	"\x05query\x18\x01 \x01(\bR\x05query\x12\x18\n" +
	"\aheaders\x18\x02 \x01(\bR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\bR\x04body\x12&\n" +
	"\x0fmax_query_bytes\x18\x04 \x01(\x05R\rmaxQueryBytes\x12(\n" +
	"\x10max_header_bytes\x18\x05 \x01(\x05R\x0emaxHeaderBytes\x12$\n" +
	"\x0emax_body_bytes\x18\x06 \x01(\x05R\fmaxBodyBytes\x12$\n" +
	"\x0emax_json_depth\x18\a \x01(\x05R\fmaxJsonDepth\x12*\n" +
	"\x11max_json_elements\x18\b \x01(\x05R\x0fmaxJsonElements2_\n" +
	"\x14ConfigurationService\x12G\n" +
	"\x04Sync\x12\x1c.controlplane.v1.SyncRequest\x1a\x1d.controlplane.v1.SyncResponse(\x010\x01BBZ@github.com/Nuryanfa/AegisGate/api/controlplane/v1;controlplanev1b\x06proto3"

var (
	file_controlplane_v1_configuration_proto_rawDescOnce sync.Once
	file_controlplane_v1_configuration_proto_rawDescData []byte
)

func file_controlplane_v1_configuration_proto_rawDescGZIP() []byte {
	file_controlplane_v1_configuration_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_configuration_proto_rawDesc), len(file_controlplane_v1_configuration_proto_rawDesc)))
	})
	return file_controlplane_v1_configuration_proto_rawDescData
}

var file_controlplane_v1_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_controlplane_v1_configuration_proto_goTypes = []any{
	(*SyncRequest)(nil),           // 0: controlplane.v1.SyncRequest
	(*SyncResponse)(nil),          // 1: controlplane.v1.SyncResponse
	(*Registration)(nil),          // 2: controlplane.v1.Registration
	(*Acknowledgement)(nil),       // 3: controlplane.v1.Acknowledgement
	(*Rejection)(nil),             // 4: controlplane.v1.Rejection
	(*Heartbeat)(nil),             // 5: controlplane.v1.Heartbeat
	(*ConfigurationSnapshot)(nil), // 6: controlplane.v1.ConfigurationSnapshot
	(*DynamicConfiguration)(nil),  // 7: controlplane.v1.DynamicConfiguration
	(*ApiClient)(nil),             // 8: controlplane.v1.ApiClient
	(*Route)(nil),                 // 9: controlplane.v1.Route
	(*AuthenticationPolicy)(nil),  // 10: controlplane.v1.AuthenticationPolicy
	(*RateLimitPolicy)(nil),       // 11: controlplane.v1.RateLimitPolicy
	(*WafPolicy)(nil),             // 12: controlplane.v1.WafPolicy
	(*InspectionPolicy)(nil),      // 13: controlplane.v1.InspectionPolicy
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_controlplane_v1_configuration_proto_depIdxs = []int32{
	2,  // 0: controlplane.v1.SyncRequest.registration:type_name -> controlplane.v1.Registration
	3,  // 1: controlplane.v1.SyncRequest.ack:type_name -> controlplane.v1.Acknowledgement
	4,  // 2: controlplane.v1.SyncRequest.nack:type_name -> controlplane.v1.Rejection
	5,  // 3: controlplane.v1.SyncRequest.heartbeat:type_name -> controlplane.v1.Heartbeat
	6,  // 4: controlplane.v1.SyncResponse.snapshot:type_name -> controlplane.v1.ConfigurationSnapshot
	5,  // 5: controlplane.v1.SyncResponse.heartbeat:type_name -> controlplane.v1.Heartbeat
	14, // 6: controlplane.v1.ConfigurationSnapshot.generated_at:type_name -> google.protobuf.Timestamp
	7,  // 7: controlplane.v1.ConfigurationSnapshot.configuration:type_name -> controlplane.v1.DynamicConfiguration
	8,  // 8: controlplane.v1.DynamicConfiguration.api_clients:type_name -> controlplane.v1.ApiClient
	9,  // 9: controlplane.v1.DynamicConfiguration.routes:type_name -> controlplane.v1.Route
	10, // 10: controlplane.v1.Route.auth:type_name -> controlplane.v1.AuthenticationPolicy
	11, // 11: controlplane.v1.Route.rate_limit:type_name -> controlplane.v1.RateLimitPolicy
	12, // 12: controlplane.v1.Route.waf:type_name -> controlplane.v1.WafPolicy
	13, // 13: controlplane.v1.WafPolicy.inspection:type_name -> controlplane.v1.InspectionPolicy
	0,  // 14: controlplane.v1.ConfigurationService.Sync:input_type -> controlplane.v1.SyncRequest
	1,  // 15: controlplane.v1.ConfigurationService.Sync:output_type -> controlplane.v1.SyncResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_controlplane_v1_configuration_proto_init() }
func file_controlplane_v1_configuration_proto_init() {
	if File_controlplane_v1_configuration_proto != nil {
		return
	}
	file_controlplane_v1_configuration_proto_msgTypes[0].OneofWrappers = []any{
		(*SyncRequest_Registration)(nil),
		(*SyncRequest_Ack)(nil),
		(*SyncRequest_Nack)(nil),
		(*SyncRequest_Heartbeat)(nil),
	}
	file_controlplane_v1_configuration_proto_msgTypes[1].OneofWrappers = []any{
		(*SyncResponse_Snapshot)(nil),
		(*SyncResponse_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_configuration_proto_rawDesc), len(file_controlplane_v1_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_v1_configuration_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_configuration_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_configuration_proto_msgTypes,
	}.Build()
	File_controlplane_v1_configuration_proto = out.File
	file_controlplane_v1_configuration_proto_goTypes = nil
	file_controlplane_v1_configuration_proto_depIdxs = nil
}
